### ISSUE TITLE
passport-oauth2에서 제공하는 state auto generate/validate 기능을 사용할 수 없음

### ISSUE THREAD

**Issue by mooyoul** [naver/passport-naver#4]
[passport-oauth2](https://github.com/jaredhanson/passport-oauth2/blob/master/lib/strategy.js#L143) 은 자동으로 state [state (See: http://tools.ietf.org/html/rfc6749#section-4.1.1)](http://tools.ietf.org/html/rfc6749#section-4.1.1)를 생성하고 검증하는 기능을 포함하고 있습니다.
(OAuth 2의 표준 규격인 RFC6749에서 강제하지는 않지만, CSRF 공격을 막기 위해 권장하고 있는 사항)

하지만, `passport-naver`에서는 해당 기능을 사용할 수 없습니다.
왜냐하면, [authorizationURL]은 query string이 포함되지 않은 path, 즉 pathname이어야하기 떄문입니다.

실제로 OAuth의 authorize가 수행되는 곳은 [passport-oauth2 패키지 내부의 authenticate 메소드](https://github.com/jaredhanson/passport-oauth2/blob/master/lib/strategy.js#L226-L227)이고,

여기서 최종 authorizationURL을 OAuth2 패키지의 [getAuthorizeUrl 메소드](https://github.com/ciaranj/node-oauth/blob/master/lib/oauth2.js#L156-L160)를 통해 URL을 빌드하게 됩니다.

즉, authorize의 Request시 URL에 포함되는 query parameter는 [passport-oauth2 의 authorizationParams 메소드](https://github.com/jaredhanson/passport-oauth2/blob/master/lib/strategy.js#L205)
를 통해서 빌드해야 하는것입니다.

하지만 현재 관련된 [`passport-naver`의 코드](https://github.com/naver/passport-naver/blob/master/lib/strategy.js#L14-L16)를 보면, URL 빌드를 직접 string에 일일히 붙이게 되어 잘못된 URL (Malformed URL)을 생성하고, 이로 인해 state parameter가 OAuth Provider측에서 무시되는 게 아닌가 추측됩니다.

**Comment by nstopkimsk** [comment]
## NAVER - http://www.naver.com/

김성관(sungkwan.kim@naverco...) 님은 현재 부재중입니다.</br>
보내신 메일 <[passport-naver] passport-oauth2에서 제공하는 state auto generate/validate 기능을 사용할 수 없음 (#4)> 은 저장되어 있으므로 다시 보내실 필요는 없습니다.</br>

## 김성관(sungkwan.kim@naverco...) 님이 남기신 메시지 입니다.

## [Absence period : 2015-07-03 10:00 ~ 2015-07-03 19:00 GMT +09:00]<br>부재중입니다. 급한 용무는 김진녕님에게 연락부탁드립니다

**Comment by mooyoul** [comment]
확인결과 [passport-oauth2 패키지에서 제공하는 해당 state generation/validation 기능은 v1.0.0부터 지원하는 기능](https://github.com/jaredhanson/passport-facebook/issues/14#issuecomment-22733478)이지만,

[passport-naver의 package.json을 확인해보니 passport-oauth 패키지 버전이 구버전](https://github.com/naver/passport-naver/blob/205e337cb344b8f13665cca4351b95aec42e29cb/package.json#L45)이여서 지원하지 않았던 것으로 확인됩니다.

**Comment by nstopkimsk** [comment]
## NAVER - http://www.naver.com/

김성관(sungkwan.kim@naverco...) 님은 현재 부재중입니다.</br>
보내신 메일 <Re: [passport-naver] passport-oauth2에서 제공하는 state auto generate/validate 기능을 사용할 수 없음 (#4)> 은 저장되어 있으므로 다시 보내실 필요는 없습니다.</br>

## 김성관(sungkwan.kim@naverco...) 님이 남기신 메시지 입니다.

## [Absence period : 2015-07-03 10:00 ~ 2015-07-03 19:00 GMT +09:00]<br>부재중입니다. 급한 용무는 김진녕님에게 연락부탁드립니다
